name: Waka Readme

on: [workflow_dispatch]
#   schedule:
    # Runs at 12am IST
#     - cron: '00 19 * * */2'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: True
          SHOW_PROJECTS: True
          SHOW_EDITORS: False
          SHOW_TIMEZONE: False
          SHOW_COMMIT: True
          SHOW_LANGUAGE: True
          SHOW_LINES_OF_CODE: True
          SHOW_LOC_CHART: False
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_DAYS_OF_WEEK: False
          SHOW_SHORT_INFO: False
          SHOW_PROFILE_VIEWS: True
